/**
 * Comprehensive Biomarker Threshold Configuration
 * 
 * Defines clinical reference ranges and deviation detection rules for 50+ biomarker types.
 * Used by the Daily Insights system to analyze lab results and generate health insights.
 */

export interface BiomarkerThreshold {
  type: string; // Biomarker type (matches database 'type' field)
  displayName: string;
  minPercentageDeviation: number; // Minimum % change from baseline to trigger insight
  criticalPercentageDeviation: number; // Threshold for critical alerts
  direction: 'both' | 'increase' | 'decrease'; // Which direction matters
  unit: string;
  description: string;
  // Clinical reference ranges
  referenceRange?: {
    low: number;
    high: number;
  };
}

/**
 * All supported biomarker thresholds
 * Organized by category for clarity
 */
export const BIOMARKER_THRESHOLDS: Record<string, BiomarkerThreshold> = {
  // ============================================================================
  // LIPID PANEL
  // ============================================================================
  'ldl-cholesterol': {
    type: 'ldl-cholesterol',
    displayName: 'LDL Cholesterol',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'increase', // Only increases matter for LDL
    unit: 'mg/dL',
    description: 'LDL Cholesterol (bad cholesterol)',
    referenceRange: { low: 0, high: 100 }, // Optimal < 100 mg/dL
  },
  'hdl-cholesterol': {
    type: 'hdl-cholesterol',
    displayName: 'HDL Cholesterol',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'decrease', // Only decreases matter for HDL
    unit: 'mg/dL',
    description: 'HDL Cholesterol (good cholesterol)',
    referenceRange: { low: 40, high: 60 },
  },
  'total-cholesterol': {
    type: 'total-cholesterol',
    displayName: 'Total Cholesterol',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Total Cholesterol',
    referenceRange: { low: 0, high: 200 },
  },
  'cholesterol': {
    type: 'cholesterol',
    displayName: 'Total Cholesterol',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Total Cholesterol',
    referenceRange: { low: 0, high: 200 },
  },
  'triglycerides': {
    type: 'triglycerides',
    displayName: 'Triglycerides',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Triglycerides',
    referenceRange: { low: 0, high: 150 },
  },
  'vldl-cholesterol': {
    type: 'vldl-cholesterol',
    displayName: 'VLDL Cholesterol',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'VLDL Cholesterol',
    referenceRange: { low: 2, high: 30 },
  },

  // ============================================================================
  // LIVER FUNCTION
  // ============================================================================
  'alt': {
    type: 'alt',
    displayName: 'ALT',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'increase',
    unit: 'U/L',
    description: 'Alanine Aminotransferase (liver enzyme)',
    referenceRange: { low: 7, high: 56 },
  },
  'ast': {
    type: 'ast',
    displayName: 'AST',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'increase',
    unit: 'U/L',
    description: 'Aspartate Aminotransferase (liver enzyme)',
    referenceRange: { low: 10, high: 40 },
  },
  'alp': {
    type: 'alp',
    displayName: 'ALP',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'U/L',
    description: 'Alkaline Phosphatase',
    referenceRange: { low: 44, high: 147 },
  },
  'alkaline-phosphatase': {
    type: 'alkaline-phosphatase',
    displayName: 'Alkaline Phosphatase',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'U/L',
    description: 'Alkaline Phosphatase',
    referenceRange: { low: 44, high: 147 },
  },
  'bilirubin': {
    type: 'bilirubin',
    displayName: 'Bilirubin',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Total Bilirubin',
    referenceRange: { low: 0.1, high: 1.2 },
  },
  'total-bilirubin': {
    type: 'total-bilirubin',
    displayName: 'Total Bilirubin',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Total Bilirubin',
    referenceRange: { low: 0.1, high: 1.2 },
  },
  'albumin': {
    type: 'albumin',
    displayName: 'Albumin',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'g/dL',
    description: 'Albumin (liver protein)',
    referenceRange: { low: 3.5, high: 5.5 },
  },
  'ggt': {
    type: 'ggt',
    displayName: 'GGT',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'increase',
    unit: 'U/L',
    description: 'Gamma-Glutamyl Transferase',
    referenceRange: { low: 9, high: 48 },
  },
  'gamma-gt': {
    type: 'gamma-gt',
    displayName: 'Gamma-GT',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'increase',
    unit: 'U/L',
    description: 'Gamma-Glutamyl Transferase',
    referenceRange: { low: 9, high: 48 },
  },
  'total-protein': {
    type: 'total-protein',
    displayName: 'Total Protein',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'g/dL',
    description: 'Total Protein',
    referenceRange: { low: 6.0, high: 8.3 },
  },
  'globulin': {
    type: 'globulin',
    displayName: 'Globulin',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'g/dL',
    description: 'Globulin',
    referenceRange: { low: 2.0, high: 3.5 },
  },

  // ============================================================================
  // KIDNEY FUNCTION
  // ============================================================================
  'creatinine': {
    type: 'creatinine',
    displayName: 'Creatinine',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Creatinine (kidney function)',
    referenceRange: { low: 0.7, high: 1.3 },
  },
  'bun': {
    type: 'bun',
    displayName: 'BUN',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Blood Urea Nitrogen',
    referenceRange: { low: 7, high: 20 },
  },
  'urea': {
    type: 'urea',
    displayName: 'Urea',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'increase',
    unit: 'mmol/L',
    description: 'Urea',
    referenceRange: { low: 2.5, high: 7.1 },
  },
  'egfr': {
    type: 'egfr',
    displayName: 'eGFR',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'decrease', // Decreases in eGFR matter
    unit: 'mL/min/1.73m²',
    description: 'Estimated Glomerular Filtration Rate',
    referenceRange: { low: 90, high: 120 },
  },
  'uric-acid': {
    type: 'uric-acid',
    displayName: 'Uric Acid',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Uric Acid',
    referenceRange: { low: 3.5, high: 7.2 },
  },

  // ============================================================================
  // BLOOD COUNTS (HEMATOLOGY)
  // ============================================================================
  'rbc': {
    type: 'rbc',
    displayName: 'RBC',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'M/μL',
    description: 'Red Blood Cell Count',
    referenceRange: { low: 4.5, high: 5.9 },
  },
  'wbc': {
    type: 'wbc',
    displayName: 'WBC',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'K/μL',
    description: 'White Blood Cell Count',
    referenceRange: { low: 4.5, high: 11.0 },
  },
  'hemoglobin': {
    type: 'hemoglobin',
    displayName: 'Hemoglobin',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'g/dL',
    description: 'Hemoglobin',
    referenceRange: { low: 13.5, high: 17.5 },
  },
  'haemoglobin': {
    type: 'haemoglobin',
    displayName: 'Haemoglobin',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'g/dL',
    description: 'Haemoglobin',
    referenceRange: { low: 13.5, high: 17.5 },
  },
  'hematocrit': {
    type: 'hematocrit',
    displayName: 'Hematocrit',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: '%',
    description: 'Hematocrit',
    referenceRange: { low: 38.8, high: 50.0 },
  },
  'hct': {
    type: 'hct',
    displayName: 'HCT',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: '%',
    description: 'Hematocrit',
    referenceRange: { low: 38.8, high: 50.0 },
  },
  'platelets': {
    type: 'platelets',
    displayName: 'Platelets',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'K/μL',
    description: 'Platelet Count',
    referenceRange: { low: 150, high: 400 },
  },
  'mcv': {
    type: 'mcv',
    displayName: 'MCV',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'fL',
    description: 'Mean Corpuscular Volume',
    referenceRange: { low: 80, high: 100 },
  },
  'mch': {
    type: 'mch',
    displayName: 'MCH',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'pg',
    description: 'Mean Corpuscular Hemoglobin',
    referenceRange: { low: 27, high: 33 },
  },
  'mchc': {
    type: 'mchc',
    displayName: 'MCHC',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'g/dL',
    description: 'Mean Corpuscular Hemoglobin Concentration',
    referenceRange: { low: 32, high: 36 },
  },
  'rdw': {
    type: 'rdw',
    displayName: 'RDW',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'increase',
    unit: '%',
    description: 'Red Cell Distribution Width',
    referenceRange: { low: 11.5, high: 14.5 },
  },
  'mpv': {
    type: 'mpv',
    displayName: 'MPV',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'fL',
    description: 'Mean Platelet Volume',
    referenceRange: { low: 7.5, high: 11.5 },
  },
  'neutrophils': {
    type: 'neutrophils',
    displayName: 'Neutrophils',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: '%',
    description: 'Neutrophils',
    referenceRange: { low: 40, high: 70 },
  },
  'lymphocytes': {
    type: 'lymphocytes',
    displayName: 'Lymphocytes',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: '%',
    description: 'Lymphocytes',
    referenceRange: { low: 20, high: 40 },
  },
  'monocytes': {
    type: 'monocytes',
    displayName: 'Monocytes',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: '%',
    description: 'Monocytes',
    referenceRange: { low: 2, high: 8 },
  },
  'eosinophils': {
    type: 'eosinophils',
    displayName: 'Eosinophils',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: '%',
    description: 'Eosinophils',
    referenceRange: { low: 1, high: 4 },
  },
  'basophils': {
    type: 'basophils',
    displayName: 'Basophils',
    minPercentageDeviation: 50,
    criticalPercentageDeviation: 100,
    direction: 'both',
    unit: '%',
    description: 'Basophils',
    referenceRange: { low: 0, high: 1 },
  },

  // ============================================================================
  // THYROID FUNCTION
  // ============================================================================
  'tsh': {
    type: 'tsh',
    displayName: 'TSH',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'mIU/L',
    description: 'Thyroid Stimulating Hormone',
    referenceRange: { low: 0.4, high: 4.0 },
  },
  't3': {
    type: 't3',
    displayName: 'T3',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'ng/dL',
    description: 'Triiodothyronine (T3)',
    referenceRange: { low: 80, high: 200 },
  },
  't4': {
    type: 't4',
    displayName: 'T4',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'μg/dL',
    description: 'Thyroxine (T4)',
    referenceRange: { low: 5.0, high: 12.0 },
  },
  'free-t3': {
    type: 'free-t3',
    displayName: 'Free T3',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Free Triiodothyronine',
    referenceRange: { low: 2.3, high: 4.2 },
  },
  'free-t4': {
    type: 'free-t4',
    displayName: 'Free T4',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'ng/dL',
    description: 'Free Thyroxine',
    referenceRange: { low: 0.8, high: 1.8 },
  },

  // ============================================================================
  // DIABETES / GLUCOSE METABOLISM
  // ============================================================================
  'hba1c': {
    type: 'hba1c',
    displayName: 'HbA1c',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'increase',
    unit: '%',
    description: 'Hemoglobin A1c (3-month glucose average)',
    referenceRange: { low: 4, high: 5.6 },
  },
  'blood-glucose': {
    type: 'blood-glucose',
    displayName: 'Blood Glucose',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Blood Glucose',
    referenceRange: { low: 70, high: 140 },
  },
  'glucose': {
    type: 'glucose',
    displayName: 'Glucose',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Glucose',
    referenceRange: { low: 70, high: 140 },
  },
  'fasting-glucose': {
    type: 'fasting-glucose',
    displayName: 'Fasting Glucose',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Fasting Blood Glucose',
    referenceRange: { low: 70, high: 100 },
  },
  'insulin': {
    type: 'insulin',
    displayName: 'Insulin',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'μIU/mL',
    description: 'Fasting Insulin',
    referenceRange: { low: 2.6, high: 24.9 },
  },

  // ============================================================================
  // VITAMINS & MINERALS
  // ============================================================================
  'vitamin-d': {
    type: 'vitamin-d',
    displayName: 'Vitamin D',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Vitamin D (25-OH)',
    referenceRange: { low: 30, high: 100 },
  },
  'vitamin-b12': {
    type: 'vitamin-b12',
    displayName: 'Vitamin B12',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Vitamin B12',
    referenceRange: { low: 200, high: 900 },
  },
  'folate': {
    type: 'folate',
    displayName: 'Folate',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Folate (Folic Acid)',
    referenceRange: { low: 2.7, high: 17.0 },
  },
  'iron': {
    type: 'iron',
    displayName: 'Iron',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'μg/dL',
    description: 'Serum Iron',
    referenceRange: { low: 60, high: 170 },
  },
  'ferritin': {
    type: 'ferritin',
    displayName: 'Ferritin',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Ferritin (iron storage)',
    referenceRange: { low: 24, high: 336 },
  },
  'transferrin': {
    type: 'transferrin',
    displayName: 'Transferrin',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Transferrin',
    referenceRange: { low: 200, high: 360 },
  },
  'transferrin-saturation': {
    type: 'transferrin-saturation',
    displayName: 'Transferrin Saturation',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: '%',
    description: 'Transferrin Saturation',
    referenceRange: { low: 20, high: 50 },
  },
  'calcium': {
    type: 'calcium',
    displayName: 'Calcium',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Serum Calcium',
    referenceRange: { low: 8.5, high: 10.5 },
  },
  'corrected-calcium': {
    type: 'corrected-calcium',
    displayName: 'Corrected Calcium',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Corrected Calcium',
    referenceRange: { low: 8.5, high: 10.5 },
  },
  'adjusted-calcium': {
    type: 'adjusted-calcium',
    displayName: 'Adjusted Calcium',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Adjusted Calcium',
    referenceRange: { low: 8.5, high: 10.5 },
  },
  'magnesium': {
    type: 'magnesium',
    displayName: 'Magnesium',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Serum Magnesium',
    referenceRange: { low: 1.7, high: 2.2 },
  },
  'phosphate': {
    type: 'phosphate',
    displayName: 'Phosphate',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'mg/dL',
    description: 'Serum Phosphate',
    referenceRange: { low: 2.5, high: 4.5 },
  },

  // ============================================================================
  // INFLAMMATION MARKERS
  // ============================================================================
  'crp': {
    type: 'crp',
    displayName: 'CRP',
    minPercentageDeviation: 50,
    criticalPercentageDeviation: 100,
    direction: 'increase',
    unit: 'mg/L',
    description: 'C-Reactive Protein (inflammation)',
    referenceRange: { low: 0, high: 3.0 },
  },
  'hscrp': {
    type: 'hscrp',
    displayName: 'hs-CRP',
    minPercentageDeviation: 50,
    criticalPercentageDeviation: 100,
    direction: 'increase',
    unit: 'mg/L',
    description: 'High-Sensitivity C-Reactive Protein',
    referenceRange: { low: 0, high: 1.0 },
  },
  'esr': {
    type: 'esr',
    displayName: 'ESR',
    minPercentageDeviation: 40,
    criticalPercentageDeviation: 80,
    direction: 'increase',
    unit: 'mm/hr',
    description: 'Erythrocyte Sedimentation Rate',
    referenceRange: { low: 0, high: 20 },
  },

  // ============================================================================
  // ELECTROLYTES
  // ============================================================================
  'sodium': {
    type: 'sodium',
    displayName: 'Sodium',
    minPercentageDeviation: 5,
    criticalPercentageDeviation: 10,
    direction: 'both',
    unit: 'mmol/L',
    description: 'Serum Sodium',
    referenceRange: { low: 136, high: 145 },
  },
  'potassium': {
    type: 'potassium',
    displayName: 'Potassium',
    minPercentageDeviation: 10,
    criticalPercentageDeviation: 20,
    direction: 'both',
    unit: 'mmol/L',
    description: 'Serum Potassium',
    referenceRange: { low: 3.5, high: 5.0 },
  },
  'chloride': {
    type: 'chloride',
    displayName: 'Chloride',
    minPercentageDeviation: 5,
    criticalPercentageDeviation: 10,
    direction: 'both',
    unit: 'mmol/L',
    description: 'Serum Chloride',
    referenceRange: { low: 98, high: 107 },
  },
  'bicarbonate': {
    type: 'bicarbonate',
    displayName: 'Bicarbonate',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'mmol/L',
    description: 'Serum Bicarbonate',
    referenceRange: { low: 22, high: 29 },
  },
  'anion-gap': {
    type: 'anion-gap',
    displayName: 'Anion Gap',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'mmol/L',
    description: 'Anion Gap',
    referenceRange: { low: 8, high: 16 },
  },

  // ============================================================================
  // HORMONES
  // ============================================================================
  'testosterone': {
    type: 'testosterone',
    displayName: 'Testosterone',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'both',
    unit: 'ng/dL',
    description: 'Total Testosterone',
    referenceRange: { low: 300, high: 1000 },
  },
  'free-testosterone': {
    type: 'free-testosterone',
    displayName: 'Free Testosterone',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Free Testosterone',
    referenceRange: { low: 9, high: 30 },
  },
  'shbg': {
    type: 'shbg',
    displayName: 'SHBG',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'nmol/L',
    description: 'Sex Hormone Binding Globulin',
    referenceRange: { low: 13, high: 71 },
  },
  'estrogen': {
    type: 'estrogen',
    displayName: 'Estrogen',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Estrogen (Estradiol)',
    referenceRange: { low: 15, high: 350 },
  },
  'estradiol': {
    type: 'estradiol',
    displayName: 'Estradiol',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Estradiol (E2)',
    referenceRange: { low: 10, high: 40 }, // For men
  },
  'oestradiol': {
    type: 'oestradiol',
    displayName: 'Oestradiol',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'pg/mL',
    description: 'Oestradiol (E2)',
    referenceRange: { low: 10, high: 40 },
  },
  'progesterone': {
    type: 'progesterone',
    displayName: 'Progesterone',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Progesterone',
    referenceRange: { low: 0.1, high: 25 },
  },
  'cortisol': {
    type: 'cortisol',
    displayName: 'Cortisol',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'μg/dL',
    description: 'Serum Cortisol (morning)',
    referenceRange: { low: 6, high: 23 },
  },
  'serum-cortisol': {
    type: 'serum-cortisol',
    displayName: 'Serum Cortisol',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'μg/dL',
    description: 'Serum Cortisol',
    referenceRange: { low: 6, high: 23 },
  },
  'dhea-sulphate': {
    type: 'dhea-sulphate',
    displayName: 'DHEA-S',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'μg/dL',
    description: 'DHEA Sulfate',
    referenceRange: { low: 80, high: 560 }, // For men 30-39
  },
  'fsh': {
    type: 'fsh',
    displayName: 'FSH',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'mIU/mL',
    description: 'Follicle Stimulating Hormone',
    referenceRange: { low: 1.5, high: 12.4 }, // For men
  },
  'follicle-stimulating-hormone': {
    type: 'follicle-stimulating-hormone',
    displayName: 'Follicle Stimulating Hormone',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'mIU/mL',
    description: 'Follicle Stimulating Hormone',
    referenceRange: { low: 1.5, high: 12.4 },
  },
  'lh': {
    type: 'lh',
    displayName: 'LH',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'mIU/mL',
    description: 'Luteinizing Hormone',
    referenceRange: { low: 1.7, high: 8.6 }, // For men
  },
  'luteinizing-hormone': {
    type: 'luteinizing-hormone',
    displayName: 'Luteinizing Hormone',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'mIU/mL',
    description: 'Luteinizing Hormone',
    referenceRange: { low: 1.7, high: 8.6 },
  },
  'prolactin': {
    type: 'prolactin',
    displayName: 'Prolactin',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Prolactin',
    referenceRange: { low: 4, high: 15 }, // For men
  },
  'igf-1': {
    type: 'igf-1',
    displayName: 'IGF-1',
    minPercentageDeviation: 20,
    criticalPercentageDeviation: 40,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Insulin-like Growth Factor 1',
    referenceRange: { low: 90, high: 360 }, // Age-dependent
  },
  'growth-hormone': {
    type: 'growth-hormone',
    displayName: 'Growth Hormone',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'both',
    unit: 'ng/mL',
    description: 'Growth Hormone',
    referenceRange: { low: 0, high: 5 },
  },

  // ============================================================================
  // OTHER MARKERS
  // ============================================================================
  'psa': {
    type: 'psa',
    displayName: 'PSA',
    minPercentageDeviation: 30,
    criticalPercentageDeviation: 60,
    direction: 'increase',
    unit: 'ng/mL',
    description: 'Prostate-Specific Antigen',
    referenceRange: { low: 0, high: 4.0 },
  },
  'ldh': {
    type: 'ldh',
    displayName: 'LDH',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'both',
    unit: 'U/L',
    description: 'Lactate Dehydrogenase',
    referenceRange: { low: 140, high: 280 },
  },
  'non-hdl-cholesterol': {
    type: 'non-hdl-cholesterol',
    displayName: 'Non-HDL Cholesterol',
    minPercentageDeviation: 15,
    criticalPercentageDeviation: 30,
    direction: 'increase',
    unit: 'mg/dL',
    description: 'Non-HDL Cholesterol',
    referenceRange: { low: 0, high: 130 },
  },
  'calcium-score': {
    type: 'calcium-score',
    displayName: 'Calcium Score',
    minPercentageDeviation: 25,
    criticalPercentageDeviation: 50,
    direction: 'increase',
    unit: 'Agatston units',
    description: 'Coronary Artery Calcium Score',
    referenceRange: { low: 0, high: 100 },
  },
};

/**
 * Get all supported biomarker types
 */
export function getSupportedBiomarkers(): string[] {
  return Object.keys(BIOMARKER_THRESHOLDS);
}

/**
 * Get threshold configuration for a biomarker type
 */
export function getBiomarkerThreshold(type: string): BiomarkerThreshold | undefined {
  return BIOMARKER_THRESHOLDS[type];
}

/**
 * Check if biomarker type is supported
 */
export function isBiomarkerSupported(type: string): boolean {
  return type in BIOMARKER_THRESHOLDS;
}
